# Get editor completions based on the config schema
"$schema" = 'config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_macchiato"

# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[󰒸](green) ❯](peach)"
error_symbol = "[[󰒸](red) ❯](peach)"
vimcmd_symbol = "[󰒸 ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

#format = """ 
#\
#[](fg:blue)\
#$os\
#[](bg:blue fg:red)\
#$username\
#[](bg:red fg:green)\
#$directory\
#[ ](fg:green)\
#$/usr/share/endeavouros/backgrounds/endeavouros-wallpaper.pnggit_branch\
#$git_status\
#$all\
#$character"""
#
#[username]
#show_always = true
#format = '[$user ](bg:red fg:black)'
#disabled = false
#
#[os]
#disabled = false
#style = 'bg:blue fg:black'
#[os.symbols]
#Alpaquita = " "
#Alpine = " "
#AlmaLinux = " "
#Amazon = " "
#Android = " "
#Artix = " "
#Arch = " "
#CachyOS = " "
#CentOS = " "
#Debian = " "
#DragonFly = " "
#Emscripten = " "
#EndeavourOS = " "
#Fedora = " "
#FreeBSD = " "
#Garuda = "󰛓 "
#Gentoo = " "
#HardenedBSD = "󰞌 "
#Illumos = "󰈸 "
#Kali = " "
#Linux = " "
#Mabox = " "
#Macos = " "
#Manjaro = " "
#Mariner = " "
#MidnightBSD = " "
#Mint = " "
#NetBSD = " "
#NixOS = " "
#Nobara = " "
#OpenBSD = "󰈺 "
#openSUSE = " "
#OracleLinux = "󰌷 "
#Pop = " "
#Raspbian = " "
#Redhat = " "
#RedHatEnterprise = " "
#RockyLinux = " "
#Redox = "󰀘 "
#Solus = "󰠳 "
#SUSE = " "
#Ubuntu = " "
#Unknown = " "
#Void = " "
#Windows = "󰍲 "
#
#[cmd_duration]
#format = "[$duration](fg:red)"
#
#[directory]
#format = "[$path](bg:green fg:black)"
#truncation_length = 2
#truncation_symbol = "…/"
#
#[character]
#success_symbol = "[](bold blue)"
#error_symbol = "[✗](bold red)"
#disabled = false
#
#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = "󰝚 "
#"Pictures" = " "
#"Scripts" = "󰲋 "
#
#[fossil_branch]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[git_branch]
#symbol = "  "
#format = '[$symbol($branch) ($version)]($style)'
#
#[git_commit]
#tag_symbol = '  '
#format = '[$symbol($version)]($style)'
#
#[aws]
#symbol = "   "
#format = '[$symbol($version)]($style)'
#
#[buf]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[c]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[cmake]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[conda]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[crystal]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[dart]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[docker_context]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[elixir]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[elm]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[fennel]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[golang]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[guix_shell]
#symbol = "   "
#format = '[$symbol($version)]($style)'
#
#[haskell]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[haxe]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[hg_branch]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[hostname]
#ssh_symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[java]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[julia]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[kotlin]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[lua]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[memory_usage]
#symbol = " 󰍛 "
#format = '[$symbol($version)]($style)'
#
#[meson]
#symbol = " 󰔷 "
#format = '[$symbol($version)]($style)'
#
#[nim]
#symbol = " 󰆥 "
#format = '[$symbol($version)]($style)'
#
#[nix_shell]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[nodejs]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[ocaml]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[package]
#symbol = " 󰏗 "
#format = '[$symbol($version)]($style)'
#
#[perl]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[php]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[pijul_channel]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[python]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[rlang]
#symbol = " 󰟔 "
#format = '[$symbol($version)]($style)'
#
#[ruby]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[rust]
#symbol = " 󱘗 "
#format = '[$symbol($version)]($style)'
#
#[scala]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[swift]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[zig]
#symbol = "  "
#format = '[$symbol($version)]($style)'
#
#[gradle]
#symbol = "  "
#format = '[$symbol($version)]($style)'
